### PR TITLE
Read data from material wrap modes, MinFilter, and Magfilter.

### PR DESCRIPTION
**Pull request by MichaelHinrichs**
Read data from material wrap modes, MinFilter, and Magfilter.

### CODE REVIEW

**Comment by MichaelHinrichs** [comment]
Read data from material wrap modes, MinFilter, and Magfilter.

**Comment by MichaelHinrichs** [comment]
Crud. so the title is the part that genraly describes what changd, and the body is a feature iv never sceen because I never botherd to click on coments. Now my pull reqest is generic and undiscriptive. pleas be nice, i'm new at this.

**Comment by libertyernie** [comment]
I had to revert this because it didn't compile properly (due to references to undeclared variables.) Feel free to submit another one once you get it fixed.

**Comment by MichaelHinrichs** [comment]
I forgot some code erlyer in the file than the big main change I made. just 4 tiny easily missed lines. I skimmed right over them, forgetting thay wher mine. I'll try again with the declarations now. hopefully that's ALL I'm forgetting.

**Comment by MichaelHinrichs** [comment]
https://github.com/libertyernie/brawltools/pull/198

**Comment by MichaelHinrichs** [comment]
fixed.
[https://github.com/libertyernie/brawltools/pull/198](url)

**Pull request merged**
